export const users = [
  { id: 1, name: 'Alice Johnson', email: 'alice.johnson@example.com', role: 'admin', status: 'active' },
  { id: 2, name: 'Bob Smith', email: 'bob.smith@example.com', role: 'manager', status: 'active' },
  { id: 3, name: 'Carol White', email: 'carol.white@example.com', role: 'viewer', status: 'inactive' },
  { id: 4, name: 'David Brown', email: 'david.brown@example.com', role: 'manager', status: 'active' },
  { id: 5, name: 'Eve Davis', email: 'eve.davis@example.com', role: 'viewer', status: 'active' },
  { id: 6, name: 'Frank Miller', email: 'frank.miller@example.com', role: 'admin', status: 'active' },
  { id: 7, name: 'Grace Wilson', email: 'grace.wilson@example.com', role: 'manager', status: 'inactive' },
  { id: 8, name: 'Henry Moore', email: 'henry.moore@example.com', role: 'viewer', status: 'active' },
  { id: 9, name: 'Ivy Taylor', email: 'ivy.taylor@example.com', role: 'manager', status: 'active' },
  { id: 10, name: 'Jack Anderson', email: 'jack.anderson@example.com', role: 'viewer', status: 'active' },
  { id: 11, name: 'Kate Thomas', email: 'kate.thomas@example.com', role: 'admin', status: 'inactive' },
  { id: 12, name: 'Leo Jackson', email: 'leo.jackson@example.com', role: 'manager', status: 'active' },
  { id: 13, name: 'Mia Harris', email: 'mia.harris@example.com', role: 'viewer', status: 'active' },
  { id: 14, name: 'Noah Martin', email: 'noah.martin@example.com', role: 'admin', status: 'active' },
  { id: 15, name: 'Olivia Garcia', email: 'olivia.garcia@example.com', role: 'viewer', status: 'inactive' },
  { id: 16, name: 'Peter Rodriguez', email: 'peter.rodriguez@example.com', role: 'manager', status: 'active' },
  { id: 17, name: 'Quinn Lee', email: 'quinn.lee@example.com', role: 'viewer', status: 'active' },
  { id: 18, name: 'Rachel Clark', email: 'rachel.clark@example.com', role: 'admin', status: 'active' },
  { id: 19, name: 'Sam Lewis', email: 'sam.lewis@example.com', role: 'manager', status: 'inactive' },
  { id: 20, name: 'Tina Walker', email: 'tina.walker@example.com', role: 'viewer', status: 'active' },
  { id: 21, name: 'Ulrich Hall', email: 'ulrich.hall@example.com', role: 'manager', status: 'active' },
  { id: 22, name: 'Violet Young', email: 'violet.young@example.com', role: 'viewer', status: 'active' },
  { id: 23, name: 'Walter King', email: 'walter.king@example.com', role: 'admin', status: 'inactive' },
  { id: 24, name: 'Xena Wright', email: 'xena.wright@example.com', role: 'viewer', status: 'active' },
  { id: 25, name: 'Yara Lopez', email: 'yara.lopez@example.com', role: 'manager', status: 'active' },
]
